### ISSUE TITLE
Bypass loop assertion error

### ISSUE THREAD

**Issue by syed-ahmed** [zslwyuan/Light-HLS#1]
Hi Tingyuan! First of all, great work!

I am trying to run Light-HLS on the `bin_conv` function of Rosetta benchmarks. I modified the bin_conv function based on the examples you have in the project: https://gist.github.com/syed-ahmed/10b113ae40c4e1b1c7a86ddf0cbf7052. I am hitting the following error:

```
bypass loop without label tmp_loop_name=_Z8bin_convPA2341_11clang_apint_64_i11clang_apint_16_iPA2_A1024_S_11clang_apint_1_jS6_j11clang_apint_16_jS6_11clang_apint_2_jS8_.for.body434-for.body434
Light_HLS_Top: /home/stahmed/workspace/code/Light-HLS/Implementations/HI_LoopUnroll/HI_LoopUnroll.cc:222: virtual bool HI_LoopUnroll::runOnLoop(llvm::Loop*, llvm::LPPassManager&): Assertion `false && "bypass loop without label tmp_loop_name. Each loop should has its own label. In the evaluation test, each loop will be set with label automatically while in other tests, the loops might need to be set with labels manually."' failed.
Aborted (core dumped)
```
I can see that in `tmp_loopLabeled.cc`, all loops are getting labelled. So wondering what does this assertion error really mean. Any help is appreciated! :)

**Comment by zslwyuan** [comment]
Hi Ahmed,

Sorry for the delay since I was on a trip. I am not sure whether you have solved the problem and I fail to open the link in your issue.

If you can provide the source code you tested with Light-HLS, I will dig out the problem and solve it for you!! ^_^

Thanks,

Tingyuan

**Comment by zslwyuan** [comment]
Hi Syed,

Thanks for your report of issue and currently I think the latest version of Light-HLS is able to process your code. However, since in your code, the trip counts of some loops are dependent on the inputs of the functions, Light-HLS might not be able to provide an accurate evaluation for these cases. However, by checking the output "HI_WithDirectiveTimingResourceEvaluation__forCheck_0", you can still analyze the scheduling, especially for those predictable loops. 

Moreover, please note that, if those inputs, e.g. width_mode and norm_mode are known during compilation, some loops will be eliminated. 

We will keep upgrading our tool for these situations and our next step is to modify clang to meet the requirements of FPGA designs. 

Tingyuan

**Comment by zslwyuan** [comment]
The bug is caused by Hi_IR2SourceCode, since in yhe IR code, some basic blocks share lines in the source code, which we might not be able to get the accurate ranges of the loops in the source code, simply based on the label metadata. 

We now find out the index variants of the loops to locate the loops' beginning lines, assuming that all the loops are for-loop.

**Comment by syed-ahmed** [comment]
Thanks so much Tingyuan! I have verified that the latest code runs analysis on bin_conv, and am getting the following output:
```
Hi-LLVM INFO:   Done latency evaluation of top function: [bin_conv] and its latency is 10568 the state num is: 125 and its resource cost is [DSP=3, FF=4346, LUT=9717, BRAM=65]
```
I don't see anything in "HI_WithDirectiveTimingResourceEvaluation__forCheck_0" though, but I guess I can figure it out from here. Thanks again for being so quick on supporting this! Feel free to close this issue.

**Comment by zslwyuan** [comment]
Hi Syed,

    You can add “DEBUG” at the end of your command line and many information will be dumped to different log file. ^_^
